# blue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  labels:
    app: my-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: blue
  template:
    metadata:
      labels:
        app: my-app
        version: blue
    spec:
      containers:
        - name: my-app-container
          image: 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:blue # Replace with your blue version image
          ports:
            - containerPort: 80
