version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 533267380341.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t ijse-assigment .
      - docker tag ijse-assigment:latest 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:latest
  post_build:
    commands:
      - docker push 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
