version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 533267380341.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ijse-assigment .
      - echo Tagging the current green image as blue if it exists...
      - docker pull 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:green || true
      - docker tag 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:green 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:blue || true
      - echo Tagging the Docker image as green...
      - docker tag ijse-assigment:latest 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:green
  post_build:
    commands:
      - echo Pushing the Docker image with blue tag to ECR if it exists...

      - docker push 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:blue || true
      - docker push 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:green
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
