# green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  labels:
    app: my-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
        - name: my-app-container
          image: 533267380341.dkr.ecr.ap-south-1.amazonaws.com/ijse-assigment:green # Replace with your green version image
          ports:
            - containerPort: 80
